export const SLIDE_HEX = {
  chart1: "#C8102E",
  chart2: "#1C2430",
  chart3: "#0F766E",
  chart4: "#EA580C",
  chart5: "#2563EB",
  chart6: "#7C3AED",
  chart7: "#16A34A",
  chart8: "#DB2777",
  black: "#000000",
  sky: "#0EA5E9",
  amber: "#CA8A04",
  slate: "#475569",
  purple: "#9333EA",
  white: "#FFFFFF",
  paper: "#F8FAFC",
  grid: "#E2E8F0",
  gridSoft: "#F1F5F9",
  slate300: "#CBD5E1",
  slate400: "#94A3B8",
  slate500: "#64748B",
  ink: "#0B1220",
  slate700: "#334155",
  danger: "#DC2626",
  dangerDark: "#991B1B",
  dangerSoft: "#FEE2E2",
  dangerWash: "#FEF2F2",
  dangerBorder: "#FCA5A5",
  success: "#16A34A",
  successDark: "#065F46",
  successSoft: "#D1FAE5",
  blue: "#3B82F6",
  blueDark: "#1D4ED8",
  blueSoft: "#BFDBFE",
  warningDark: "#D97706",
  forecastOrange: "#F59E0B",
  cyanDark: "#0891B2",
  pinkDark: "#BE185D",
  neutralDark: "#111827",
} as const;

export const SLIDE_CSS = {
  chart1: "hsl(var(--chart-1))",
  chart2: "hsl(var(--chart-2))",
  chart3: "hsl(var(--chart-3))",
  chart4: "hsl(var(--chart-4))",
  chart5: "hsl(var(--chart-5))",
  chart6: "hsl(var(--chart-6))",
  chart7: "hsl(var(--chart-7))",
  chart8: "hsl(var(--chart-8))",
  background: "hsl(var(--background))",
  foreground: "hsl(var(--foreground))",
  card: "hsl(var(--card))",
  border: "hsl(var(--border))",
  muted: "hsl(var(--muted))",
  mutedForeground: "hsl(var(--muted-foreground))",
  primary: "hsl(var(--primary))",
  success: "hsl(var(--success))",
  destructive: "hsl(var(--destructive))",
  editorSelection: "hsl(var(--editor-selection))",
  editorGuide: "hsl(var(--editor-guide))",
  editorPreflightError: "hsl(var(--editor-preflight-error))",
} as const;

export const SLIDE_RGBA = {
  editorSelectionBorder: "hsl(var(--editor-selection) / 0.55)",
  editorSelectionBorderSoft: "hsl(var(--editor-selection) / 0.35)",
  editorSelectionBg: "hsl(var(--editor-selection) / 0.08)",
  editorSelectionBadge: "hsl(var(--editor-selection) / 0.82)",
  editorSelectionBadgeStrong: "hsl(var(--editor-selection) / 0.92)",
  editorSelectionPillBg: "hsl(var(--editor-selection) / 0.12)",
  editorSelectionPillBorder: "hsl(var(--editor-selection) / 0.35)",
  incomingBadgeBg: "hsl(var(--editor-selection) / 0.85)",
  haraldWash: "hsl(var(--chart-1) / 0.08)",
  haraldGlow: "hsl(var(--chart-1) / 0.65)",
  darkOverlay: "hsl(0 0% 0% / 0.55)",
  darkOverlayStrong: "hsl(0 0% 0% / 0.72)",
  whiteOverlay: "hsl(0 0% 100% / 0.12)",
} as const;

export const SLIDE_CHART_PALETTE = [
  SLIDE_HEX.chart1,
  SLIDE_HEX.chart2,
  SLIDE_HEX.chart3,
  SLIDE_HEX.chart6,
  SLIDE_HEX.chart4,
  SLIDE_HEX.chart5,
  SLIDE_HEX.sky,
  SLIDE_HEX.chart7,
  SLIDE_HEX.chart8,
  SLIDE_HEX.amber,
  SLIDE_HEX.slate,
  SLIDE_HEX.purple,
];

export const SLIDE_BRAND_COLORS = [
  SLIDE_HEX.chart1,
  SLIDE_HEX.chart2,
  SLIDE_HEX.white,
  SLIDE_HEX.paper,
  SLIDE_HEX.slate500,
  SLIDE_HEX.chart3,
  SLIDE_HEX.chart5,
  SLIDE_HEX.chart4,
];

export const SLIDE_HARALD_PALETTE = [
  SLIDE_HEX.chart1,
  SLIDE_HEX.chart2,
  SLIDE_HEX.chart3,
  SLIDE_HEX.chart4,
  SLIDE_HEX.chart5,
  SLIDE_HEX.chart6,
  SLIDE_HEX.chart7,
  SLIDE_HEX.chart8,
];
